travis:
  secure:
    BINSTAR_TOKEN: I0wRCPF1nIlzcXTxmVAhd2IKV/T3qsL6Fkc+SFsV2V4xGrhImp61MYGf+ynx0y3Tel9lwluBQANO0ZsWVd6c/41erflVn8QENa52gRnrzUcLV0Yag8IKuvJkBEeieR+ZgvnVwRTvbc8+PvqEX4MzhLNEpJQKDJ97qhMpUWUos7sizd+euITJdQDeimVSekhE+OpnOk9O0S89Zr7AublxmUtFkKynKQYl5WZe1GSxukaH12jndMdKSu+3uDgGNl5b8upcJWxJGVD4cU2uSVrpMju3hLWv9OwwR87YNxBizPggUTA80v7bcJ9gw0hB8WmsKS4j8T2JIlcvtn/HJsiAqlNp6wfAheTjNq+4HLKDww0GchlBFvc594s86K9TYFLFd9zByWbTvCvzph0YyGThBnegH+EBpbXbIiAfH79SYpkugcfMGrzKztqLDFf+Ujm7vpOw2N+kTABBa4h4eTeIm4N+Tf8iFYiC712M9rPc5/bz+LZ+zsCoS4Tht6YhstpgfFZMgLvEYKLESJaI6T7OvoFAr71KSTDJBZGDg+NUChKbQwiXNpQbT0qfFCLqUojfVoVmLRGL8KkJ5ukuG1QwXjaU71KSN35A+mL0IApDz9s9YzuuRswCb0q3zQCi/noQd2W2/w+k7kxFJx98MklTowLEDZDqrPSvYo39bUqeNXs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
